import type { RichProductDetail } from "@/lib/content/product-details";

export const MPV7_DETAIL: RichProductDetail = {
  id: "mpv7",
  officialName: "VinFast VF MPV 7",
  segment: "MPV 7 chỗ (Multi-Purpose Vehicle) — Xe điện đại gia đình",
  shortName: "VF MPV 7",
  h1: "VinFast VF MPV 7 Cần Thơ: MPV Điện 7 Chỗ — Thông Số & Giá 2026",
  metaTitle:
    "VinFast VF MPV 7 Cần Thơ: MPV Điện 7 Chỗ, 450 km, Thông Số Kỹ Thuật",
  metaDescription:
    "VinFast VF MPV 7 tại Cần Thơ — MPV điện 7 chỗ giá niêm yết 750 triệu (đã kèm pin). Quãng đường 450 km NEDC, công suất 150 kW, miễn phí sạc đến 06/2027. Tư vấn tại Cần Thơ GF.",
  keywords: [
    "vinfast vf mpv 7",
    "mpv7 cần thơ",
    "vf mpv 7",
    "mpv điện 7 chỗ vinfast",
    "xe điện 7 chỗ cần thơ",
    "mpv7 giá",
    "mua mpv7 cần thơ",
  ],
  image: "/mpv7.webp",
  imageAlt: "VinFast VF MPV 7 — MPV điện 7 chỗ tại Cần Thơ GF",
  listPrice: 750_000_000,
  listPriceLabel: "750.000.000 VNĐ (Tiêu chuẩn — đã kèm pin)",
  priceVariants: [
    {
      id: "mpv7-standard",
      name: "VF MPV 7 Tiêu chuẩn",
      listPrice: 750_000_000,
      promoPrice: 750_000_000,
    },
  ],
  positioningHtml: `<p><strong>VinFast VF MPV 7</strong> là MPV điện <strong>7 chỗ</strong> thế hệ mới — lựa chọn lý tưởng cho <strong>đại gia đình tại Cần Thơ</strong> cần không gian rộng, hành trình êm ái và quãng đường <strong>450 km</strong> mỗi lần sạc. Xe dài nhất trong dòng VinFast (4.740 mm), công suất 150 kW, treo sau đa liên kết cao cấp và <strong>miễn phí sạc pin đến hết 06/2027</strong> (theo điều kiện chương trình).</p>`,
  highlights: [
    "Giá niêm yết 750 triệu (đã kèm pin) — phiên bản Tiêu chuẩn",
    "MPV 7 chỗ duy nhất trong dòng xe điện VinFast",
    "Quãng đường 450 km NEDC — pin 60,13 kWh, sạc nhanh 30 phút (10%–70%)",
    "Công suất 150 kW, mô-men xoắn 280 Nm — tương đương xe xăng 2.0L",
    "Treo sau đa liên kết cao cấp, la-zăng 19 inch — lớn nhất trong dòng",
    "Miễn phí sạc pin đến hết tháng 06/2027 (theo điều khoản)",
    "Bảo hành xe 7 năm, pin 8 năm — cứu hộ 24/7",
  ],
  specGroups: [
    {
      id: "kich-thuoc",
      heading: "Kích thước & khung gầm",
      headingLevel: 3,
      specs: [
        {
          label: "Dài x Rộng x Cao (mm)",
          value: "4.740 x 1.872 x 1.734",
        },
        { label: "Chiều dài cơ sở (mm)", value: "2.840" },
        { label: "Khoảng sáng gầm (mm)", value: "185" },
        { label: "Trọng lượng không tải (kg)", value: "1.875" },
        { label: "Số chỗ ngồi", value: "7 chỗ" },
      ],
    },
    {
      id: "dong-co",
      heading: "Động cơ & truyền động",
      headingLevel: 3,
      specs: [
        { label: "Công suất tối đa", value: "150 kW" },
        { label: "Mô-men xoắn cực đại", value: "280 Nm" },
        { label: "Dẫn động", value: "Cầu trước (FWD)" },
        { label: "Chế độ lái", value: "Eco / Normal / Sport" },
        { label: "Phanh tái sinh", value: "Có" },
        { label: "Cần chuyển số sau vô lăng", value: "Có" },
      ],
    },
    {
      id: "pin-sac",
      heading: "Pin & sạc",
      headingLevel: 3,
      specs: [
        { label: "Dung lượng pin", value: "60,13 kWh" },
        { label: "Quãng đường (NEDC)", value: "450 km" },
        { label: "Sạc nhanh DC (10%–70%)", value: "30 phút" },
        { label: "Sạc chậm AC tối đa", value: "6,9 kW" },
        { label: "Sạc nhanh DC tối đa", value: "80 kW" },
        { label: "Bộ sạc tại nhà (phụ kiện)", value: "7,4 kW" },
        { label: "Dây sạc di động (phụ kiện)", value: "3,5 kW" },
      ],
    },
    {
      id: "treo-phanh",
      heading: "Khung gầm & hệ thống treo",
      headingLevel: 3,
      specs: [
        { label: "Treo trước", value: "MacPherson độc lập" },
        { label: "Treo sau", value: "Đa liên kết cao cấp" },
        { label: "Phanh trước", value: "Đĩa thông gió" },
        { label: "Phanh sau", value: "Đĩa" },
        { label: "Phanh tay", value: "Điện tử & tự động giữ phanh" },
        { label: "Trợ lực lái", value: "Trợ lực điện" },
        { label: "La-zăng / lốp", value: "Hợp kim 19 inch — 235/50 R19" },
      ],
    },
  ],
  batteryHighlight:
    "450 km mỗi lần sạc — quãng đường dài nhất trong dòng VinFast, lý tưởng cho gia đình Cần Thơ thường xuyên du lịch dài hoặc di chuyển liên huyện. Sạc nhanh DC chỉ 30 phút (10%–70%).",
  batterySectionTitle: "Pin, Sạc & Ưu Đãi Miễn Phí Sạc",
  chargingInfrastructure: [
    { label: "Miễn phí sạc pin", value: "Đến hết tháng 06/2027" },
    { label: "Sạc tại nhà", value: "7,4 kW (phụ kiện chính hãng)" },
    { label: "Sạc di động", value: "3,5 kW (phụ kiện chính hãng)" },
    { label: "Sạc nhanh DC", value: "Tối đa 80 kW — 30 phút (10%–70%)" },
  ],
  chargingSolutionItems: [
    "Sạc tại nhà 7,4 kW — tiện lợi, sạc overnight cho sử dụng hàng ngày",
    "Sạc di động 3,5 kW — mang theo khi du lịch, linh hoạt mọi nơi",
    "Sạc nhanh DC 80 kW — 10%–70% chỉ 30 phút, phù hợp chuyến đi dài",
    "Sạc chậm AC 6,9 kW — tiết kiệm năng lượng, dùng dài hạn",
    "Miễn phí sạc pin đến 06/2027 — áp dụng điều kiện & điều khoản chương trình",
  ],
  exteriorColors: [
    { id: "zenith-grey", name: "Zenith Grey", nameVi: "Xám", hex: "#6B7280" },
    {
      id: "introspective-brown",
      name: "Introspective Brown",
      nameVi: "Nâu",
      hex: "#5C4033",
    },
    {
      id: "moonlit-ocean",
      name: "Moonlit Ocean",
      nameVi: "Xanh dương",
      hex: "#1E3A5F",
    },
    {
      id: "infinity-blanc",
      name: "Infinity Blanc",
      nameVi: "Trắng",
      hex: "#F5F5F0",
    },
    { id: "jet-black", name: "Jet Black", nameVi: "Đen", hex: "#1A1A1A" },
    { id: "solar-ruby", name: "Solar Ruby", nameVi: "Đỏ", hex: "#8B1A2B" },
  ],
  interiorColors: [
    {
      id: "granite-black",
      name: "Granite Black",
      nameVi: "Đen",
      hex: "#2D2D2D",
    },
    {
      id: "mocca-brown",
      name: "Mocca Brown",
      nameVi: "Nâu",
      hex: "#6B4423",
    },
  ],
  exteriorFeatureList: [
    "Thiết kế MPV sành điệu, hiện đại — xe dài nhất dòng VinFast (4.740 mm)",
    "Đèn pha LED tự động bật/tắt, đèn hậu LED, đèn nhận diện & DRL",
    "Gương chỉnh/gập điện tích hợp báo rẽ, gạt mưa gián đoạn",
    "Thanh trang trí nóc xe (phụ kiện), kính cửa điện một chạm, kính chắn gió chống UV",
    "Camera lùi & cảm biến đỗ xe phía sau",
  ],
  interiorFeatureList: [
    "7 ghế da nhân tạo — ghế 2 gập 60:40, ghế 3 gập lưng có tựa đầu",
    "Vô lăng D-cut da, chỉnh cơ 4 hướng, cần số tích hợp sau vô lăng",
    "Màn hình trung tâm 10,1 inch cảm ứng, Apple CarPlay & Android Auto",
    "Điều hòa tự động 1 vùng, cửa gió hàng 2 & 3, sưởi kính sau, lọc PM2.5",
    "USB-A & USB-C hàng 1 & 2, sạc 12V hàng 1 và cốp sau, đèn trần hàng 1 & 2",
    "ISOFIX hàng 2, khóa cửa trẻ em hàng 2 & 3, bảng đỡ sau lưng ghế trước",
  ],
  featureSections: [
    {
      id: "tro-ly-ao",
      heading: "Trợ Lý Ảo & Công Nghệ Thông Minh",
      headingLevel: 2,
      items: [
        "Trợ lý ảo điều khiển bằng giọng nói — tương tác tự nhiên",
        "3 chế độ lái Eco / Normal / Sport, quản lý Bluetooth & eSIM",
        "Giám sát pin, hồ sơ người lái, FOTA, chế độ Cắm trại",
        "Trình duyệt web, tự chẩn đoán lỗi từ xa",
      ],
    },
    {
      id: "vinfast-app",
      heading: "Ứng Dụng VinFast (C-App)",
      headingLevel: 2,
      items: [
        "Đồng bộ tài khoản, nhận thông báo, giám sát xe từ xa",
        "Tìm trạm sạc, hỗ trợ hậu mãi & bảo dưỡng",
      ],
    },
    {
      id: "an-toan",
      heading: "Hệ Thống An Toàn",
      headingLevel: 2,
      items: [
        "4 túi khí: trước (2) + bên hông (2)",
        "ABS, EBD, BA, ESC, TCS, HSA, ROM, ESS, ga tự động cơ bản",
        "Khóa cửa tự động, khóa cửa trẻ em, ITPMS, cảnh báo chống trộm",
        "Căng đai khẩn cấp, cảnh báo dây an toàn, camera lùi & cảm biến đỗ",
      ],
    },
    {
      id: "van-hanh",
      heading: "Khả Năng Vận Hành",
      headingLevel: 2,
      items: [
        "150 kW / 280 Nm — vận hành ổn định, tương đương xe xăng 2.0L",
        "450 km NEDC — quãng đường dài nhất VinFast, giảm lo âu về pin",
        "Treo sau đa liên kết cao cấp — hành trình êm ái cho 7 chỗ",
        "Phanh tái sinh — hiệu suất cao, tiết kiệm năng lượng",
      ],
    },
    {
      id: "so-sanh",
      heading: "So Sánh Với Các Dòng VinFast",
      headingLevel: 2,
      items: [
        "VF 3: Mini Car, 4 chỗ, 215 km — đô thị nhỏ gọn",
        "VF 5: A-SUV, 5 chỗ, 326 km, 100 kW — đô thị năng động",
        "VF 6: C-SUV, 5 chỗ, 485 km, 150 kW, 7 túi khí — gia đình trẻ",
        "VF MPV 7: MPV 7 chỗ, 450 km, 150 kW — đại gia đình & du lịch dài",
      ],
    },
  ],
  warrantyItems: [
    "Bảo hành xe: 7 năm hoặc 160.000 km (điều kiện nào đến trước)",
    "Bảo hành pin: 8 năm hoặc 160.000 km",
    "Miễn phí sạc pin đến hết tháng 06/2027 (theo điều kiện chương trình)",
  ],
  afterSalesItems: [
    "Cứu hộ 24/7 suốt thời gian bảo hành",
    "Hệ thống Showroom & xưởng dịch vụ toàn quốc",
    "Hỗ trợ kỹ thuật chuyên nghiệp, phụ tùng chính hãng",
  ],
  targetAudience: [
    "Gia đình đông người tại Cần Thơ — 7 chỗ thoải mái cho cả nhà",
    "Người thường xuyên du lịch dài — 450 km, không lo hết pin",
    "Gia đình có trẻ em — ISOFIX, khóa cửa trẻ em, 4 túi khí",
    "Khách hàng cần không gian rộng (4.740 mm) và công nghệ hiện đại",
  ],
  disclaimerNotes: [
    "Giá niêm yết đã bao gồm pin — áp dụng theo chính sách VinFast mới nhất.",
    "Quãng đường thực tế có thể thấp hơn 450 km NEDC tùy tốc độ, nhiệt độ, địa hình, số hành khách & hành lý.",
    "Một số tính năng chưa kích hoạt tại thời điểm giao xe — cập nhật qua OTA hoặc tại xưởng dịch vụ.",
    "Hình ảnh minh họa; sản phẩm thực tế có thể khác. Chỉ dùng pin & giải pháp sạc chính hãng VinFast.",
  ],
  features: [
    "MPV điện 7 chỗ duy nhất VinFast",
    "450 km/lần sạc — pin 60,13 kWh",
    "Công suất 150 kW, treo sau đa liên kết",
    "La-zăng 19 inch, màn hình 10,1 inch",
    "Miễn phí sạc đến 06/2027",
  ],
};
