import type { RichProductDetail } from "@/lib/content/product-details";

export const VF5_DETAIL: RichProductDetail = {
  id: "vf5",
  officialName: "VinFast VF 5",
  segment: "A-SUV (Compact SUV) — Xe điện đô thị cho người trẻ năng động",
  shortName: "VF 5",
  slogan: "Cá nhân vượt trội, đồng hành hàng ngày",
  h1: "VinFast VF 5 Cần Thơ: A-SUV Điện — Giá, Thông Số & ADAS 2026",
  metaTitle:
    "VinFast VF 5 Cần Thơ: Giá 496 Triệu, Thông Số, 8 Màu & ViVi AI",
  metaDescription:
    "VinFast VF 5 tại Cần Thơ — giá 496 triệu (kèm pin). Quãng đường 326 km, 6 túi khí, ADAS, trợ lý ảo ViVi. A-SUV điện lý tưởng cho đô thị. Tư vấn tại Cần Thơ GF.",
  keywords: [
    "vinfast vf5",
    "vf5 cần thơ",
    "vf5 giá",
    "mua vf5 cần thơ",
    "a-suv điện vinfast",
    "vf5 plus",
    "xe điện đô thị cần thơ",
    "vf5 xanhsm",
    "vf5 tài xế",
    "so sánh vf5 và vf3",
  ],
  image: "/vf5.webp",
  imageAlt: "VinFast VF 5 — A-SUV điện tại Cần Thơ GF",
  listPrice: 496_000_000,
  listPriceLabel: "496.000.000 VNĐ (VF 5 Plus — đã kèm pin)",
  priceVariants: [
    {
      id: "vf5-plus",
      name: "VF 5 Plus",
      listPrice: 496_000_000,
      promoPrice: 496_000_000,
    },
  ],
  positioningHtml: `<p><strong>VinFast VF 5</strong> — <em>"Phong cách hợp ý, giá hợp ví"</em> — là xe điện đô thị lý tưởng cho người trẻ năng động tại <strong>Cần Thơ</strong>. Hội tụ thiết kế hiện đại, công nghệ thông minh (trợ lý ảo <strong>ViVi</strong>), vận hành mạnh mẽ 134 hp và an toàn 6 túi khí + ADAS.</p>`,
  highlights: [
    "Thiết kế hiện đại, độc đáo — cá nhân hóa 8 màu ngoại thất",
    "Công suất 100 kW (134 hp) — tương đương xe xăng 1,6L",
    "Quãng đường 326 km NEDC — sạc nhanh 33 phút (10%–70%)",
    "6 túi khí + ADAS 6 tính năng hỗ trợ lái",
    "Trợ lý ảo ViVi AI — nhận diện tiếng Việt 98%",
    "Bảo hành xe 7 năm, pin 8 năm — hạ tầng sạc toàn quốc",
  ],
  specGroups: [
    {
      id: "kich-thuoc",
      heading: "Kích thước & khung gầm",
      headingLevel: 3,
      specs: [
        {
          label: "Dài x Rộng x Cao (mm)",
          value: "3.967 x 1.723 x 1.579",
        },
        { label: "Chiều dài cơ sở (mm)", value: "2.514" },
        { label: "Khoảng sáng gầm (mm)", value: "160" },
        { label: "Trọng lượng không tải (kg)", value: "1.340" },
        { label: "Tải trọng (kg)", value: "325" },
        {
          label: "Khoang hành lý (lít)",
          value: "331 / 1.015 (gập ghế sau)",
        },
        { label: "Số chỗ ngồi", value: "5 ghế" },
      ],
    },
    {
      id: "dong-co",
      heading: "Động cơ & truyền động",
      headingLevel: 3,
      specs: [
        { label: "Loại động cơ", value: "1 Motor điện" },
        { label: "Công suất tối đa", value: "100 kW (134 hp)" },
        { label: "Mô-men xoắn cực đại", value: "135 Nm" },
        { label: "Tăng tốc 0–100 km/h", value: "12 giây" },
        { label: "Dẫn động", value: "FWD (Cầu trước)" },
        { label: "Chế độ lái", value: "Eco / Sport" },
      ],
    },
    {
      id: "pin-sac",
      heading: "Pin & sạc",
      headingLevel: 3,
      specs: [
        { label: "Loại pin", value: "LFP (Lithium Iron Phosphate)" },
        { label: "Dung lượng pin khả dụng", value: "37,23 kWh" },
        { label: "Quãng đường (NEDC)", value: "326,4 km / 326 km" },
        { label: "Tiêu thụ công khai", value: "13 kWh/100 km" },
        { label: "Sạc nhanh nhất (10%–70%)", value: "33 phút" },
      ],
    },
    {
      id: "treo-phanh",
      heading: "Khung gầm & hệ thống treo",
      headingLevel: 3,
      specs: [
        { label: "Treo trước", value: "Độc lập, MacPherson" },
        { label: "Treo sau", value: "Dầm xoắn" },
        { label: "Hệ thống phanh", value: "Đĩa thông gió / đĩa" },
        { label: "Trợ lực lái", value: "EPS / Trợ lực điện" },
        { label: "La-zăng", value: "Hợp kim 17 inch" },
      ],
    },
  ],
  batteryHighlight:
    "326 km mỗi lần sạc — đủ cho tài xế XanhSM và gia đình Cần Thơ di chuyển cả ngày. Mạng lưới 150.000 cổng sạc toàn quốc, khoảng cách trung bình 3,5 km giữa các trạm trong thành phố.",
  batterySectionTitle: "Pin, Sạc & Hạ Tầng Toàn Quốc",
  chargingInfrastructure: [
    { label: "Cổng sạc toàn quốc", value: "150.000 cổng sạc" },
    { label: "Khoảng cách trạm trong TP", value: "Trung bình 3,5 km" },
    { label: "Giải pháp sạc", value: "Tại nhà · Trụ nhanh · Bộ di động" },
    { label: "Chương trình V-Green", value: "Miễn phí sạc (theo điều khoản)" },
  ],
  chargingSolutionItems: [
    "Bộ sạc tại nhà — sạc mọi lúc, tiện lợi và an toàn",
    "Trụ sạc nhanh phủ khắp toàn quốc",
    "Bộ sạc di động — mang theo trên mọi hành trình",
    "Ứng dụng VinFast: tìm trạm sạc → chọn trạm → bản đồ → chỉ đường",
  ],
  exteriorColors: [
    { id: "solar-ruby", name: "Solar Ruby", nameVi: "Đỏ", hex: "#8B1A2B" },
    {
      id: "summer-yellow",
      name: "Summer Yellow",
      nameVi: "Vàng hè",
      hex: "#F5D547",
    },
    { id: "jet-black", name: "Jet Black", nameVi: "Đen đậm", hex: "#1A1A1A" },
    {
      id: "infinity-blanc",
      name: "Infinity Blanc",
      nameVi: "Trắng vô cực",
      hex: "#F5F5F0",
    },
    {
      id: "urban-mint",
      name: "Urban Mint",
      nameVi: "Xanh lá nhạt",
      hex: "#98D4BB",
    },
    { id: "zenith-grey", name: "Zenith Grey", nameVi: "Xám", hex: "#6B7280" },
    { id: "sky-blue", name: "Sky Blue", nameVi: "Xanh trời", hex: "#5B9BD5" },
    {
      id: "infinity-blanc-roof",
      name: "Infinity Blanc Roof",
      nameVi: "Nóc trắng",
      hex: "#E8E8E8",
    },
  ],
  exteriorFeatureList: [
    "Thiết kế chữ V mạ crom — dải đèn LED định vị hiện đại",
    "Phối màu hai tông thân & nóc xe — ốp gương, tay nắm cửa đồng màu",
    "Đuôi xe vuông vức — dải chữ V phản quang, cảm biến đỗ & camera lùi",
    "La-zăng hợp kim 17 inch, gương chỉnh điện tích hợp báo rẽ",
    "Kính chắn gió chống UV, cửa sổ chỉnh điện một chạm (cửa tài xế)",
  ],
  interiorFeatureList: [
    "Thiết kế tối giản — phối màu đồng điệu nội ngoại thất",
    "Hai màn hình: đồng hồ kỹ thuật số 7 inch + màn trung tâm 8 inch cảm ứng",
    "Ghế giả da — lái chỉnh cơ 6 hướng, phụ 4 hướng, ghế sau gập 60:40",
    "Điều hòa chỉnh cơ 1 vùng, lọc bụi PM2.5, tan sương/tan băng",
    "4 loa, Android Auto & Apple CarPlay không dây, USB & Bluetooth",
  ],
  featureSections: [
    {
      id: "vivi-ai",
      heading: "Trợ Lý Ảo ViVi (AI Sinh Sản)",
      headingLevel: 2,
      items: [
        "Độ chính xác 98% nhận diện tiếng Việt đa vùng miền",
        "Điều khiển bằng giọng nói: điều hòa, giải trí, bản đồ và hơn thế",
        "Hỏi đáp tin tức, thời tiết, truyện cười — tương tác tự nhiên, cá nhân hóa",
      ],
    },
    {
      id: "adas",
      heading: "Hệ Thống ADAS (6 Tính Năng Hỗ Trợ Lái)",
      headingLevel: 2,
      items: [
        "Giám sát hành trình cơ bản & ga tự động",
        "Cảnh báo giao thông phía sau, điểm mù, mở cửa",
        "Hỗ trợ đỗ phía sau — cảm biến phát hiện chướng ngại vật",
      ],
    },
    {
      id: "thong-minh",
      heading: "Tính Năng Thông Minh & Ứng Dụng VinFast",
      headingLevel: 2,
      items: [
        "Chẩn đoán lỗi tự động, đồng bộ hồ sơ người lái",
        "Mua sắm trực tuyến trên xe, điều khiển smart home",
        "C-App: giám sát xe từ xa, tìm trạm sạc, thanh toán, đặt lịch bảo dưỡng",
      ],
    },
    {
      id: "an-toan",
      heading: "Hệ Thống An Toàn",
      headingLevel: 2,
      items: [
        "6 túi khí: trước (2), rèm (2), bên hông trước (2)",
        "ABS, EBD, BA, ESC, TCS, HSA, ESS",
        "Khóa cửa tự động, ITPMS, cảnh báo chống trộm",
        "Căng đai khẩn cấp, ISOFIX ghế trẻ em, cảnh báo thắt dây an toàn",
      ],
    },
    {
      id: "chi-phi",
      heading: "So Sánh Chi Phí Với Xe Xăng",
      headingLevel: 2,
      items: [
        "Chi phí sạc thấp — chương trình miễn phí sạc V-Green (theo điều khoản)",
        "Tiết kiệm đáng kể so với xăng RON 95 (~33.840đ/lít) hoặc Diesel",
        "VF 5 đã được kiểm chứng qua hàng trăm ngàn xe bán ra tại Việt Nam",
      ],
    },
  ],
  warrantyItems: [
    "Bảo hành xe: 7 năm hoặc 160.000 km (điều kiện nào đến trước)",
    "Bảo hành pin cao áp: 8 năm hoặc 160.000 km",
    "Nền tảng khung gầm toàn cầu VinFast — chất lượng kiểm chứng",
  ],
  afterSalesItems: [
    "Cứu hộ bằng xe kéo (RSA) — cứu hộ 24/7 trong thời gian bảo hành",
    "Showroom & xưởng dịch vụ không ngày nghỉ",
    "Mạng lưới 150.000 cổng sạc toàn quốc",
  ],
  targetAudience: [
    "Người trẻ năng động tại Cần Thơ — sinh viên, nhân viên văn phòng, tài xế XanhSM",
    "Gia đình 4–5 người cần A-SUV điện giá hợp lý",
    "Khách hàng lần đầu chuyển sang xe điện — \"phong cách hợp ý, giá hợp ví\"",
  ],
  disclaimerNotes: [
    "Thông tin sản phẩm có thể thay đổi mà không cần báo trước.",
    "Một số tính năng chưa kích hoạt tại thời điểm giao xe — cập nhật qua OTA, kết nối không dây hoặc tại xưởng dịch vụ VinFast.",
    "Quãng đường thực tế có thể thấp hơn NEDC tùy tốc độ, nhiệt độ, địa hình, thói quen lái và số hành khách.",
  ],
  features: [
    "A-SUV điện bán chạy nhất Cần Thơ — phù hợp XanhSM & gia đình",
    "Giá 496 triệu kèm pin — không thuê pin",
    "ViVi AI + ADAS 6 tính năng",
    "326 km/lần sạc, la-zăng 17 inch",
    "8 màu ngoại thất cá nhân hóa",
  ],
};
