import type { RichProductDetail } from "@/lib/content/product-details";

export const VF7_DETAIL: RichProductDetail = {
  id: "vf7",
  officialName: "VinFast VF 7",
  segment: "C-SUV điện (Coupe-SUV) — Better Choice Awards 2024",
  shortName: "VF 7",
  slogan: "Mẫu xe hàng đầu phân khúc",
  h1: "VinFast VF 7 Cần Thơ: Coupe-SUV Điện — Giá Eco/Plus/AWD 2026",
  metaTitle:
    "VinFast VF 7 Cần Thơ: Giá Eco & Plus, AWD 349 hp, ADAS 20 Tính Năng",
  metaDescription:
    "VinFast VF 7 tại Cần Thơ: Eco từ 678,54 triệu, Plus từ 764,54 triệu. Bản AWD 349 hp, mô-men xoắn 500 Nm, ADAS 20 tính năng, bảo hành 10 năm và miễn phí sạc đến 10/02/2029.",
  keywords: [
    "vinfast vf7",
    "vf7 cần thơ",
    "vf7 eco",
    "vf7 plus",
    "vf7 awd",
    "xe điện coupe suv vinfast",
    "mua vf7 cần thơ",
    "vf7 vs vf6",
  ],
  image: "/vf7.webp",
  imageAlt: "VinFast VF 7 — Coupe-SUV điện tại Cần Thơ GF",
  listPrice: 789_000_000,
  listPriceLabel: "789.000.000 VNĐ (VF 7 Eco — giá gốc)",
  promoPrice: 678_540_000,
  promoPriceLabel: "678.540.000 VNĐ",
  promoVoucherLabel: "Ưu đãi VF 7 Eco",
  positioningHtml: `<p><strong>VinFast VF 7</strong> là C-SUV điện phong cách coupe với triết lý thiết kế <em>"Vũ Trụ Phi Đối Xứng"</em>, lấy cảm hứng từ vũ trụ và vật thể bay. Xe đạt <strong>Better Choice Awards 2024</strong>, nổi bật nhờ thiết kế cá tính, hiệu suất cao (bản AWD đạt <strong>260 kW / 349 hp</strong>, mô-men xoắn <strong>500 Nm</strong>) cùng gói an toàn <strong>ADAS 20 tính năng</strong>.</p>`,
  highlights: [
    "Giá ưu đãi: Eco từ 678,54 triệu · Plus từ 764,54 triệu",
    "VF 7 Plus AWD: 260 kW / 349 hp, mô-men xoắn 500 Nm",
    "ADAS 20 tính năng + 7 túi khí (Plus/AWD)",
    "Thiết kế coupe SUV theo triết lý Vũ Trụ Phi Đối Xứng",
    "Bảo hành xe & pin 10 năm / 200.000 km",
    "Miễn phí sạc đến 10/02/2029, miễn lệ phí trước bạ 2 năm",
  ],
  priceVariants: [
    {
      id: "vf7-eco",
      name: "VF 7 Eco",
      listPrice: 789_000_000,
      promoPrice: 678_540_000,
    },
    {
      id: "vf7-plus",
      name: "VF 7 Plus",
      listPrice: 889_000_000,
      promoPrice: 764_540_000,
    },
    {
      id: "vf7-plus-glass-roof",
      name: "VF 7 Plus Trần Kính Toàn Cảnh",
      listPrice: 909_000_000,
      promoPrice: 781_740_000,
    },
  ],
  compareSpecTables: [
    {
      id: "dong-co-truyen-dong",
      heading: "Động cơ & truyền động (so sánh Eco và Plus)",
      rows: [
        { label: "Công suất tối đa", eco: "130 kW / 174 hp", plus: "150 kW / 201 hp" },
        { label: "Mô-men xoắn cực đại", eco: "250 Nm", plus: "310 Nm" },
        { label: "Dẫn động", eco: "Cầu trước (FWD)", plus: "Cầu trước (FWD)" },
        { label: "Chế độ lái", eco: "Eco / Normal / Sport", plus: "Eco / Normal / Sport" },
        { label: "Phanh tái sinh", eco: "Có", plus: "Có" },
      ],
    },
    {
      id: "pin-sac",
      heading: "Pin & sạc (so sánh Eco và Plus)",
      rows: [
        { label: "Dung lượng pin", eco: "59,6 kWh", plus: "70 kWh" },
        { label: "Quãng đường/lần sạc (NEDC)", eco: "440 km", plus: "Cập nhật sau" },
        { label: "Sạc nhanh DC (10%–70%)", eco: "25 phút", plus: "28 phút" },
        { label: "Dây sạc di động", eco: "AFS 3,5 kW (phụ kiện)", plus: "AFS 3,5 kW (phụ kiện)" },
        { label: "Bộ sạc tại nhà", eco: "AFS 7,4 kW (phụ kiện)", plus: "AFS 7,4 kW (phụ kiện)" },
      ],
    },
  ],
  specGroups: [
    {
      id: "kich-thuoc",
      heading: "Kích thước & khung gầm",
      headingLevel: 3,
      specs: [
        { label: "Dài x Rộng x Cao (mm)", value: "4.545 x 1.890 x 1.635,75" },
        { label: "Chiều dài cơ sở (mm)", value: "2.840" },
        { label: "Khoảng sáng gầm (mm)", value: "190" },
      ],
    },
    {
      id: "khung-gam",
      heading: "Khung gầm & hệ thống treo",
      headingLevel: 3,
      specs: [
        { label: "Treo trước", value: "Độc lập, MacPherson" },
        { label: "Treo sau", value: "Thanh điều hướng đa điểm" },
        { label: "Phanh tay", value: "Điện tử & tự động giữ phanh" },
        { label: "Trợ lực lái", value: "Trợ lực điện" },
        { label: "La-zăng", value: "19 inch (Eco) / 20 inch (Plus)" },
      ],
    },
    {
      id: "awd",
      heading: "Thông số phiên bản VF 7 Plus AWD",
      headingLevel: 3,
      specs: [
        { label: "Công suất tối đa", value: "260 kW / 349 hp" },
        { label: "Mô-men xoắn cực đại", value: "500 Nm" },
        { label: "Dẫn động", value: "Hai cầu (AWD)" },
        { label: "Sạc nhanh DC (10%–70%)", value: "37 phút" },
        { label: "Giá bán", value: "Đang cập nhật" },
      ],
    },
  ],
  batteryHighlight:
    "VF 7 Eco đạt 440 km NEDC, bản Plus/AWD dùng pin 70 kWh. Miễn phí sạc lên đến 3 năm đến hết 10/02/2029, chi phí sạc 0 VNĐ trong thời gian ưu đãi.",
  batterySectionTitle: "Pin, Sạc & Ưu Đãi 3 Năm",
  chargingInfrastructure: [
    { label: "Mạng lưới sạc", value: "34 tỉnh/thành phố" },
    { label: "Tuyến quốc lộ", value: "106 tuyến có trạm sạc" },
    { label: "Thành phố có trạm", value: "80/85 thành phố" },
    { label: "Khoảng cách trung bình", value: "3,5 km giữa hai trạm trong thành phố" },
  ],
  chargingSolutionItems: [
    "Sạc tại nhà AFS 7,4 kW — phù hợp sạc overnight",
    "Sạc di động AFS 3,5 kW — linh hoạt khi đi xa",
    "Sạc nhanh DC: Eco 25 phút · Plus 28 phút · AWD 37 phút (10%–70%)",
    "Miễn phí lệ phí trước bạ 2 năm (theo Nghị định số 51/2025/NĐ-CP từ 01/03/2025)",
    "Miễn phí sạc pin đến hết 10/02/2029 (áp dụng điều kiện chương trình)",
  ],
  exteriorColors: [
    { id: "solar-ruby", name: "Solar Ruby", nameVi: "Đỏ", hex: "#8B1A2B" },
    { id: "zenith-grey", name: "Zenith Grey", nameVi: "Xám", hex: "#6B7280" },
    { id: "urban-mint", name: "Urban Mint", nameVi: "Xanh lá nhạt", hex: "#98D4BB" },
    { id: "infinity-blanc", name: "Infinity Blanc", nameVi: "Trắng", hex: "#F5F5F0" },
    { id: "jet-black", name: "Jet Black", nameVi: "Đen", hex: "#1A1A1A" },
  ],
  interiorColors: [
    { id: "beige", name: "Beige", nameVi: "Be", hex: "#D8C7A0" },
    { id: "mocha-brown", name: "Mocha Brown", nameVi: "Nâu", hex: "#6B4423" },
  ],
  exteriorFeatureList: [
    "Triết lý thiết kế Vũ Trụ Phi Đối Xứng — cảm hứng từ vũ trụ",
    "Dáng coupe vuốt khí động học, nắp capo thấp, thân xe cơ bắp",
    "Tay nắm cửa ẩn tăng tính liền mạch khí động học",
    "Đèn pha LED tự động bật/tắt & chiếu xa (Plus), đèn hậu LED",
    "Gương điện, gập điện, sấy gương, nhớ vị trí, chống chói tự động",
  ],
  interiorFeatureList: [
    "Khoang lái hướng người lái, không gian phóng khoáng",
    "Màn hình giải trí 12,9 inch cảm ứng, kết nối Apple CarPlay/Android Auto",
    "VF 7 Plus có HUD 12,9 inch và sạc không dây",
    "Điều hòa tự động 2 vùng, lọc Combi 1.0 + ion hóa không khí (Plus)",
    "Cốp sau lên tới 1.576L, tùy chọn trần kính toàn cảnh",
  ],
  featureSections: [
    {
      id: "an-toan",
      heading: "Hệ Thống An Toàn",
      headingLevel: 2,
      items: [
        "VF 7 Eco: 4 túi khí · VF 7 Plus/AWD: 7 túi khí",
        "ABS, EBD, BA, ESC, TCS, HSA, ROM, giám sát áp suất lốp",
        "ISOFIX hàng ghế sau, chống trộm, khóa động cơ khi có trộm",
      ],
    },
    {
      id: "adas-20",
      heading: "ADAS 20 Tính Năng (Plus/AWD)",
      headingLevel: 2,
      items: [
        "Giám sát hành trình thích ứng, cảnh báo chệch làn, hỗ trợ giữ làn",
        "Hỗ trợ chuyển làn tự động, trợ lái cao tốc, di chuyển khi tắc đường",
        "Phanh tự động khẩn cấp trước/sau, cảnh báo điểm mù và cắt ngang sau",
        "Nhận diện biển báo, cảnh báo mở cửa, camera lùi và camera 360",
      ],
    },
    {
      id: "cong-nghe",
      heading: "Hệ Thống Công Nghệ Thông Minh",
      headingLevel: 2,
      items: [
        "Chế độ Cắm trại, Người lạ, Thú cưng, Rửa xe",
        "Trợ lý ảo điều khiển chức năng xe và hỗ trợ xử lý sự cố",
        "Bản đồ EV, trình duyệt web, tiện ích thời tiết/lịch/media",
        "Ứng dụng VinFast: quản lý sạc, thanh toán, định vị xe, đặt lịch dịch vụ",
      ],
    },
    {
      id: "hieu-suat",
      heading: "Hiệu Suất Vận Hành",
      headingLevel: 2,
      items: [
        "VF 7 Eco: 130 kW / 174 hp · VF 7 Plus: 150 kW / 201 hp",
        "VF 7 Plus AWD: 260 kW / 349 hp và 500 Nm — mạnh nhất dải sản phẩm VinFast hiện tại",
        "3 chế độ lái Eco / Normal / Sport, phanh tái sinh tiết kiệm năng lượng",
        "Hệ treo đa điểm cho hành trình ổn định, êm ái ở tốc độ cao",
      ],
    },
  ],
  warrantyItems: [
    "Bảo hành xe: 10 năm hoặc 200.000 km (điều kiện nào đến trước)",
    "Bảo hành pin: 10 năm hoặc 200.000 km",
    "Chính sách bảo hành dài nhất VinFast từng cung cấp",
  ],
  afterSalesItems: [
    "Cứu hộ 24/7",
    "Xưởng dịch vụ không ngày nghỉ",
    "Sửa chữa lưu động",
    "Phụ tùng chính hãng và hỗ trợ kỹ thuật chuyên nghiệp",
  ],
  targetAudience: [
    "Người trẻ năng động yêu tốc độ và công nghệ",
    "Gia đình 5 người cần C-SUV an toàn và rộng rãi",
    "Khách hàng yêu thiết kế coupe hiện đại, cá tính",
    "Người muốn chi phí vận hành thấp nhờ ưu đãi sạc 3 năm",
  ],
  disclaimerNotes: [
    "Quãng đường thực tế có thể thấp hơn chuẩn NEDC tùy tốc độ, địa hình, nhiệt độ và thói quen lái.",
    "Một số tính năng có thể được cập nhật qua OTA hoặc kích hoạt sau tại xưởng dịch vụ.",
    "Hình ảnh mang tính minh họa. Thông số và chính sách có thể thay đổi không báo trước.",
    "Chỉ sử dụng pin và giải pháp sạc chính hãng VinFast.",
  ],
  features: [
    "Coupe-SUV điện đạt Better Choice Awards 2024",
    "Bản AWD 349 hp, mô-men xoắn 500 Nm",
    "ADAS 20 tính năng và 7 túi khí (Plus/AWD)",
    "Bảo hành 10 năm/200.000 km",
    "Miễn phí sạc đến 10/02/2029",
  ],
};
