import type { RichProductDetail } from "@/lib/content/product-details";

export const VF8_DETAIL: RichProductDetail = {
  id: "vf8",
  officialName: "VinFast VF 8",
  segment: "D-SUV (Luxury SUV 5 chỗ) — xe điện cao cấp",
  shortName: "VF 8",
  slogan: "Sự lựa chọn xứng tầm trong phân khúc SUV 5 chỗ",
  h1: "VinFast VF 8 Cần Thơ: D-SUV Điện Cao Cấp — Giá Eco & Plus 2026",
  metaTitle:
    "VinFast VF 8 Cần Thơ: Giá Eco & Plus, 402 hp, 11 Túi Khí, ViVi 2.0",
  metaDescription:
    "VinFast VF 8 tại Cần Thơ: Eco từ 898 triệu, Plus 1,079 tỷ (Pin CATL). Bản Plus 402 hp, 620 Nm, 0-100 km/h 5,58 giây, 11 túi khí, ADAS nâng cao, quãng đường 562 km (Eco).",
  keywords: [
    "vinfast vf8",
    "vf8 cần thơ",
    "vf8 eco",
    "vf8 plus",
    "xe điện d-suv vinfast",
    "mua vf8 cần thơ",
    "vf8 all new 2026",
    "vf8 vs vf9",
  ],
  image: "/vf8.webp",
  imageAlt: "VinFast VF 8 — D-SUV điện cao cấp tại Cần Thơ GF",
  listPrice: 898_000_000,
  listPriceLabel: "VF 8 Eco: 898.000.000 – 910.000.000 VNĐ · VF 8 Plus: 1.079.000.000 VNĐ (Pin CATL)",
  positioningHtml: `<p><strong>VinFast VF 8</strong> là D-SUV điện 5 chỗ theo triết lý <em>"Cân bằng động"</em>, hướng đến khách hàng cần một chiếc SUV điện cao cấp, mạnh mẽ và an toàn. Mẫu xe sở hữu công nghệ <strong>ViVi 2.0 AI</strong>, nội thất sang trọng và phiên bản Plus mạnh tới <strong>300 kW / 402 hp</strong>, mô-men xoắn <strong>620 Nm</strong>.</p>`,
  highlights: [
    "VF 8 Eco từ 898 triệu · VF 8 Plus 1,079 tỷ (Pin CATL)",
    "VF 8 Plus: 300 kW / 402 hp, mô-men xoắn 620 Nm, 0-100 km/h 5,58 giây",
    "11 túi khí trên VF 8 Plus — nổi bật trong phân khúc",
    "Pin 87,7 kWh — Eco đạt 562 km (NEDC), Plus 457 km (WLTP)",
    "ADAS nâng cao, camera 360, hỗ trợ lái cao tốc",
    "Thiết kế sang trọng, nội thất cao cấp, trợ lý ảo ViVi 2.0",
  ],
  priceVariants: [
    {
      id: "vf8-eco",
      name: "VF 8 Eco",
      listPrice: 910_000_000,
      promoPrice: 898_000_000,
    },
    {
      id: "vf8-plus",
      name: "VF 8 Plus",
      listPrice: 1_079_000_000,
      promoPrice: 1_079_000_000,
    },
  ],
  compareSpecTables: [
    {
      id: "dong-co",
      heading: "Động cơ & truyền động (Eco vs Plus)",
      rows: [
        { label: "Dẫn động", eco: "FWD (cầu trước)", plus: "AWD (hai cầu toàn thời gian)" },
        { label: "Công suất tối đa", eco: "150 kW / 201 hp", plus: "300 kW / 402 hp" },
        { label: "Mô-men xoắn", eco: "310 Nm", plus: "620 Nm" },
        { label: "0-100 km/h", eco: "11,8 giây", plus: "5,58 giây" },
        { label: "Chế độ lái", eco: "Eco / Normal / Sport", plus: "Eco / Normal / Sport" },
      ],
    },
    {
      id: "pin-sac",
      heading: "Pin & sạc (Eco vs Plus)",
      rows: [
        { label: "Dung lượng pin", eco: "87,7 kWh", plus: "87,7 kWh" },
        { label: "Quãng đường/lần sạc", eco: "562 km (NEDC)", plus: "457 km (WLTP)" },
        { label: "Sạc nhanh DC (10%-70%)", eco: "31 phút", plus: "31 phút" },
        { label: "Tiêu chuẩn đo lường", eco: "NEDC", plus: "WLTP" },
        { label: "Phanh tái sinh", eco: "Có (mặc định)", plus: "Có (mặc định)" },
      ],
    },
    {
      id: "an-toan",
      heading: "An toàn (Eco vs Plus)",
      rows: [
        { label: "Tổng số túi khí", eco: "10", plus: "11" },
        { label: "Túi khí trước lái và hành khách phía trước", eco: "2", plus: "2" },
        { label: "Túi khí rèm", eco: "2", plus: "2" },
        { label: "Túi khí bên hông hàng ghế trước", eco: "2", plus: "2" },
        { label: "Túi khí bên hông hàng ghế sau", eco: "2", plus: "2" },
        { label: "Túi khí bảo vệ chân hàng ghế trước", eco: "0", plus: "2" },
        { label: "Túi khí trung tâm hàng ghế trước", eco: "0", plus: "1" },
      ],
    },
  ],
  specGroups: [
    {
      id: "kich-thuoc",
      heading: "Kích thước & khung gầm",
      headingLevel: 3,
      specs: [
        { label: "Dài x Rộng x Cao (mm)", value: "4.750 x 1.934 x 1.667" },
        { label: "Chiều dài cơ sở (mm)", value: "2.950" },
        { label: "Khoảng sáng gầm", value: "Eco 162 mm / Plus 157 mm" },
        { label: "Trọng lượng không tải", value: "Eco 2.328 kg / Plus 2.520 kg" },
        { label: "Khoang hành lý", value: "376 L / 1.373 L (gập ghế)" },
        { label: "Khoang hành lý trước", value: "88 L" },
      ],
    },
    {
      id: "khung-treo",
      heading: "Hệ thống treo & vận hành",
      headingLevel: 3,
      specs: [
        { label: "Treo trước", value: "Treo độc lập thông minh" },
        { label: "Treo sau", value: "Thanh điều hướng đa điểm" },
        { label: "Phanh trước/sau", value: "Đĩa thông gió / Đĩa thông gió" },
        { label: "La-zăng", value: "19 inch (Eco) / 20 inch (Plus)" },
        { label: "Trợ lực lái", value: "Trợ lực điện" },
      ],
    },
  ],
  batteryHighlight:
    "VF 8 sử dụng pin 87,7 kWh, cho phạm vi 562 km (Eco theo NEDC) và 457 km (Plus theo WLTP). Sạc nhanh DC từ 10% đến 70% chỉ 31 phút.",
  batterySectionTitle: "Pin, Sạc & Hạ Tầng",
  chargingInfrastructure: [
    { label: "Mạng lưới trạm sạc", value: "Phủ 63 tỉnh/thành phố" },
    { label: "Khoảng cách trong đô thị", value: "Trung bình 3,5 km giữa 2 trạm" },
    { label: "Sạc nhanh DC", value: "31 phút (10%-70%)" },
    { label: "Hỗ trợ trên app", value: "Tìm trạm sạc, quản lý và thanh toán" },
  ],
  chargingSolutionItems: [
    "Hỗ trợ trụ sạc nhanh và bộ sạc di động",
    "Phụ kiện sạc tại nhà chính hãng sẵn có",
    "Ứng dụng VinFast hỗ trợ tìm trạm sạc và điều hướng",
    "Chi phí sạc được tối ưu theo chương trình từng thời điểm",
  ],
  exteriorColors: [
    { id: "infinity-blanc", name: "Infinity Blanc", nameVi: "Trắng", hex: "#F5F5F0" },
    { id: "jet-black", name: "Jet Black", nameVi: "Đen", hex: "#1A1A1A" },
    { id: "crimson-red", name: "Crimson Red", nameVi: "Đỏ", hex: "#8B1A2B" },
    { id: "ivy-green", name: "Ivy Green", nameVi: "Xanh lá đậm", hex: "#355E3B" },
    { id: "zenith-grey", name: "Zenith Grey", nameVi: "Xám", hex: "#6B7280" },
    { id: "crimson-velvet", name: "Crimson Velvet", nameVi: "Đỏ nhung", hex: "#6E1E2C" },
  ],
  interiorColors: [
    { id: "granite-black", name: "Granite Black", nameVi: "Đen", hex: "#2D2D2D" },
    { id: "mocha-brown", name: "Mocha Brown", nameVi: "Nâu", hex: "#6B4423" },
  ],
  exteriorFeatureList: [
    "Triết lý Cân bằng động — ngoại thất sang trọng, khí động học",
    "Đèn pha LED tự động, điều chỉnh góc chiếu thông minh",
    "VF 8 Plus có đèn sương mù trước, đèn chiếu góc và cốp điện đá chân",
    "Cửa sổ trời toàn cảnh (Plus), kính trước cách âm 2 lớp",
    "Camera 360 độ hỗ trợ xoay trở trong không gian hẹp",
  ],
  interiorFeatureList: [
    "Khoang lái tối giản tinh tế, màn hình cảm ứng trung tâm 15,6 inch",
    "VF 8 Plus: ghế lái 12 hướng, ghế phụ 10 hướng, sưởi/thông gió",
    "HUD hiển thị tốc độ, dẫn đường và cảnh báo",
    "Âm thanh 8 loa (Eco) / 10 loa + loa trầm (Plus)",
    "Sạc không dây 90W, WiFi, đèn nội thất đa màu trên bản Plus",
  ],
  featureSections: [
    {
      id: "an-toan",
      heading: "An Toàn Chủ Động & Bị Động",
      headingLevel: 2,
      items: [
        "VF 8 ECO có 10 túi khí, VF 8 PLUS có 11 túi khí",
        "Khác biệt chính: VF 8 PLUS có thêm 1 túi khí trung tâm hàng ghế trước",
        "ABS, EBD, BA, ESC, TCS, HSA, ROM, ESS, dTPMS",
        "ISOFIX hàng ghế 2, cảnh báo dây an toàn, SOS khẩn cấp",
      ],
    },
    {
      id: "adas",
      heading: "Hệ Thống ADAS Nâng Cao (Plus)",
      headingLevel: 2,
      items: [
        "Ga tự động thích ứng, trợ lái cao tốc, hỗ trợ khi ùn tắc",
        "Cảnh báo chệch làn, hỗ trợ giữ làn, kiểm soát đi giữa làn",
        "Phanh khẩn cấp tự động trước, cảnh báo va chạm trước",
        "Cảnh báo điểm mù, cắt ngang phía sau, camera 360, giám sát người lái",
      ],
    },
    {
      id: "cong-nghe",
      heading: "Công Nghệ Thông Minh & ViVi 2.0",
      headingLevel: 2,
      items: [
        "Trợ lý ảo ViVi 2.0 AI tạo sinh — tương tác tiếng Việt tự nhiên",
        "Điều khiển giọng nói, hỗ trợ tình trạng xe và xử lý sự cố",
        "OTA cập nhật tính năng mới từ xa, đồng bộ ứng dụng VinFast Mobile",
        "Giải trí trực tuyến, bản đồ EV, điều khiển xe từ xa qua app",
      ],
    },
    {
      id: "hieu-suat",
      heading: "Khả Năng Vận Hành",
      headingLevel: 2,
      items: [
        "VF 8 Eco: 150 kW / 201 hp, 310 Nm, 0-100 km/h 11,8 giây",
        "VF 8 Plus: 300 kW / 402 hp, 620 Nm, 0-100 km/h 5,58 giây",
        "Bản Plus AWD toàn thời gian cho độ bám và kiểm soát cao",
        "3 chế độ lái Eco / Normal / Sport, vận hành êm ái ổn định",
      ],
    },
  ],
  warrantyItems: [
    "Bảo hành xe: 7 năm hoặc 200.000 km (điều kiện nào đến trước)",
    "Bảo hành pin: 7 năm hoặc 200.000 km",
    "Xe thương mại: 3 năm hoặc 100.000 km",
  ],
  afterSalesItems: [
    "Cứu hộ khẩn cấp qua nút SOS tích hợp",
    "Xưởng dịch vụ không ngày nghỉ",
    "Sửa chữa lưu động, phụ tùng chính hãng",
    "Hỗ trợ kỹ thuật 24/7",
  ],
  targetAudience: [
    "Khách hàng cần SUV điện cao cấp 5 chỗ, không gian rộng",
    "Người yêu hiệu suất cao, trải nghiệm lái mạnh mẽ",
    "Gia đình ưu tiên an toàn và công nghệ hiện đại",
    "Người dùng thường xuyên di chuyển xa cần quãng đường dài",
  ],
  disclaimerNotes: [
    "Quãng đường thực tế có thể thấp hơn NEDC/WLTP tùy điều kiện sử dụng.",
    "Một số tính năng có thể cập nhật qua OTA hoặc kích hoạt sau tại xưởng.",
    "Hình ảnh mang tính minh họa; thông số và chính sách có thể thay đổi.",
    "Chỉ sử dụng pin và giải pháp sạc chính hãng VinFast.",
  ],
  features: [
    "D-SUV điện cao cấp với thiết kế sang trọng",
    "VF 8 Plus: 402 hp, 620 Nm, AWD",
    "11 túi khí và ADAS nâng cao",
    "Pin 87,7 kWh, sạc nhanh 31 phút",
    "ViVi 2.0 AI và hệ sinh thái app thông minh",
  ],
};
