import type { RichProductDetail } from "@/lib/content/product-details";

export const VF9_DETAIL: RichProductDetail = {
  id: "vf9",
  officialName: "VinFast VF 9",
  segment: "SUV Điện 7 Chỗ Hạng Sang",
  shortName: "VF 9",
  slogan: "Sự lựa chọn của người thành đạt, tiên phong",
  h1: "VinFast VF 9 Cần Thơ: SUV Điện 7 Chỗ Hạng Sang",
  metaTitle:
    "VinFast VF 9 Cần Thơ: Giá Eco/Plus, 7 Chỗ Hạng Sang, Quãng Đường 626 km",
  metaDescription:
    "VinFast VF 9 tại Cần Thơ: Eco 1,499 tỷ, Plus 1,699 tỷ, đặt cọc 50 triệu. SUV điện 7 chỗ hạng sang, pin 123 kWh, quãng đường WLTP đến 626 km, ADAS cấp độ 2, bảo hành 10 năm.",
  keywords: [
    "vinfast vf9",
    "vf9 cần thơ",
    "vf9 eco",
    "vf9 plus",
    "suv điện 7 chỗ vinfast",
    "mua vf9 cần thơ",
  ],
  image: "/vf9.webp",
  imageAlt: "VinFast VF 9 SUV điện 7 chỗ hạng sang tại Cần Thơ GF",
  listPrice: 1_499_000_000,
  listPriceLabel: "VF 9 Eco: 1.499.000.000 đ · VF 9 Plus: 1.699.000.000 đ (đã VAT)",
  depositAmount: 50_000_000,
  priceVariants: [
    {
      id: "vf9-eco",
      name: "VF 9 Eco",
      listPrice: 1_499_000_000,
      promoPrice: 1_499_000_000,
    },
    {
      id: "vf9-plus",
      name: "VF 9 Plus",
      listPrice: 1_699_000_000,
      promoPrice: 1_699_000_000,
    },
  ],
  positioningHtml: `<p><strong>VinFast VF 9</strong> là SUV điện 7 chỗ hạng sang, thiết kế bởi studio <strong>Pininfarina</strong> (Ý), lấy cảm hứng từ du thuyền hạng sang. Xe nổi bật với logo chữ V, dải đèn LED nhận diện thương hiệu, phong cách mạnh mẽ và hiện đại.</p>`,
  highlights: [
    "VF 9 Eco: 1.499.000.000 đ · VF 9 Plus: 1.699.000.000 đ (đã VAT)",
    "Đặt cọc 50.000.000 đ",
    "2 motor 150 kW, công suất 402 hp / 300 kW, mô-men xoắn 620 Nm",
    "Pin 123 kWh, quãng đường WLTP: Eco 626 km · Plus 602 km",
    "ADAS cấp độ 2 đầy đủ trên cả Eco và Plus",
    "Bảo hành xe và pin: 10 năm hoặc 200.000 km",
  ],
  compareSpecTables: [
    {
      id: "gia-ban",
      heading: "Giá bán & cấu hình",
      rows: [
        { label: "Giá niêm yết (đã VAT)", eco: "1.499.000.000 đ", plus: "1.699.000.000 đ" },
        { label: "Đặt cọc", eco: "50.000.000 đ", plus: "50.000.000 đ" },
        { label: "Tùy chọn số chỗ", eco: "7 chỗ", plus: "7 chỗ hoặc 6 chỗ" },
        { label: "Lưu ý", eco: "Giá chưa gồm ghế cơ trưởng", plus: "Giá chưa gồm ghế cơ trưởng" },
      ],
    },
    {
      id: "kich-thuoc",
      heading: "Kích thước & trọng lượng",
      rows: [
        {
          label: "Dài x Rộng x Cao (mm)",
          eco: "5.119 x 2.254 x 1.697",
          plus: "5.119 x 2.254 x 1.697",
        },
        { label: "Chiều dài cơ sở (mm)", eco: "3.149", plus: "3.149" },
        { label: "Khoảng sáng gầm xe (mm)", eco: "174", plus: "184" },
        { label: "Trọng lượng không tải (kg)", eco: "2.911", plus: "7 chỗ: 2.968 / 6 chỗ: 2.932" },
        { label: "Tải trọng (kg)", eco: "550", plus: "7 chỗ: 550 / 6 chỗ: 475" },
        { label: "Khoang hành lý có hàng ghế cuối (L)", eco: "212", plus: "212" },
        { label: "Khoang hành lý gập hàng ghế cuối (L)", eco: "926", plus: "926" },
        { label: "Khoang hành lý phía trước (L)", eco: "100", plus: "100" },
      ],
    },
    {
      id: "truyen-dong-pin",
      heading: "Hệ truyền động & pin",
      rows: [
        { label: "Động cơ", eco: "2 motor 150 kW", plus: "2 motor 150 kW" },
        { label: "Công suất tối đa", eco: "402 hp / 300 kW", plus: "402 hp / 300 kW" },
        { label: "Mô-men xoắn cực đại", eco: "620 Nm", plus: "620 Nm" },
        { label: "Hệ dẫn động", eco: "AWD - 2 cầu toàn thời gian", plus: "AWD - 2 cầu toàn thời gian" },
        { label: "Tốc độ tối đa", eco: "200 km/h", plus: "200 km/h" },
        { label: "Loại pin", eco: "CATL", plus: "CATL" },
        { label: "Dung lượng pin khả dụng", eco: "123 kWh", plus: "123 kWh" },
        { label: "Quãng đường/lần sạc (WLTP)", eco: "626 km", plus: "602 km" },
        { label: "Sạc AC tối đa", eco: "6,6 kW (1 pha) / 11 kW (3 pha)", plus: "6,6 kW (1 pha) / 11 kW (3 pha)" },
        { label: "Sạc nhanh (10-70%)", eco: "35 phút", plus: "35 phút" },
        { label: "Phanh tái sinh", eco: "Tắt / Thấp / TB / Cao", plus: "Tắt / Thấp / TB / Cao" },
        { label: "Chế độ lái", eco: "Eco / Normal / Sport", plus: "Eco / Normal / Sport" },
      ],
    },
    {
      id: "khung-gam-noi-that",
      heading: "Khung gầm & nội thất tiện nghi",
      rows: [
        { label: "Treo trước", eco: "Độc lập, tay đòn kép", plus: "Độc lập, tay đòn kép" },
        { label: "Treo sau", eco: "Liên kết đa điểm, giảm chấn khí nén", plus: "Liên kết đa điểm, giảm chấn khí nén" },
        { label: "Phanh trước/sau", eco: "Đĩa thông gió", plus: "Đĩa thông gió" },
        { label: "La-zăng", eco: "20 inch hợp kim", plus: "21 inch hợp kim" },
        { label: "Chất liệu ghế", eco: "Da nhân tạo", plus: "Da nhân tạo cao cấp" },
        { label: "Ghế lái chỉnh điện", eco: "8 hướng", plus: "12 hướng" },
        { label: "Ghế lái: massage / thông gió / sưởi", eco: "✗ / ✗ / ✓", plus: "✓ / ✓ / ✓" },
        { label: "Ghế phụ chỉnh điện", eco: "6 hướng", plus: "10 hướng" },
        { label: "Ghế phụ: massage / thông gió / sưởi", eco: "✗ / ✗ / ✓", plus: "✓ / ✓ / ✓" },
        { label: "Hàng ghế 2 chỉnh điện", eco: "4 hướng", plus: "8 hướng" },
        { label: "Hàng ghế 2: thông gió / sưởi / massage", eco: "✗ / ✗ / ✗", plus: "✓ / ✓ / ✓" },
        { label: "Màn hình trung tâm", eco: "15,6 inch", plus: "15,6 inch" },
        { label: "Màn hình hàng ghế sau", eco: "✗", plus: "8 inch" },
        { label: "Số loa", eco: "11", plus: "13 (có loa trầm & ampli)" },
      ],
    },
  ],
  specGroups: [],
  batteryHighlight:
    "VF 9 dùng pin 123 kWh, phạm vi WLTP đạt 626 km (Eco) và 602 km (Plus), hỗ trợ sạc nhanh 10-70% trong 35 phút.",
  batterySectionTitle: "Pin & Sạc",
  chargingInfrastructure: [
    { label: "Cổng sạc", value: "150.000 cổng sạc" },
    { label: "Phủ địa lý", value: "34/34 tỉnh thành" },
    { label: "Sạc miễn phí", value: "2 năm đến 30/06/2027 tại trạm công cộng VinFast" },
  ],
  chargingSolutionItems: [
    "Sạc AC tối đa 6,6 kW (1 pha) / 11 kW (3 pha)",
    "Sạc nhanh 10-70% trong 35 phút",
    "Ứng dụng điện thoại hỗ trợ tìm trạm sạc và giám sát xe",
  ],
  exteriorColors: [
    { id: "zenith-grey", name: "Zenith Grey", nameVi: "Zenith Grey", hex: "#6B7280" },
    { id: "urban-mint", name: "Urban Mint", nameVi: "Urban Mint", hex: "#98D4BB" },
    { id: "jet-black", name: "Jet Black", nameVi: "Jet Black", hex: "#1A1A1A" },
    { id: "ivy-green", name: "Ivy Green", nameVi: "Ivy Green", hex: "#355E3B" },
    { id: "infinity-blanc", name: "Infinity Blanc", nameVi: "Infinity Blanc", hex: "#F5F5F0" },
    { id: "desat-silver", name: "Desat Silver", nameVi: "Desat Silver", hex: "#B8BCC2" },
    { id: "crimson-red", name: "Crimson Red", nameVi: "Crimson Red", hex: "#8B1A2B" },
  ],
  interiorColors: [
    { id: "black", name: "Black", nameVi: "Eco: Black", hex: "#2D2D2D" },
    { id: "saddle-brown", name: "Saddle Brown", nameVi: "Plus: Black hoặc Saddle Brown", hex: "#6B4423" },
  ],
  exteriorFeatureList: [
    "Thiết kế bởi Pininfarina (Ý), cảm hứng du thuyền hạng sang",
    "Đường nét mạnh mẽ, logo chữ V và đèn LED nhận diện thương hiệu",
    "SUV điện 7 chỗ hạng sang",
  ],
  interiorFeatureList: [
    "Màn hình giải trí trung tâm 15,6 inch",
    "HUD trên cả Eco và Plus",
    "Điều hòa tự động 3 vùng",
    "Sạc không dây trên cả Eco và Plus",
    "Vô lăng D-cut, da thân thiện môi trường",
  ],
  featureSections: [
    {
      id: "an-toan",
      heading: "An Toàn",
      headingLevel: 2,
      items: [
        "11 túi khí trên cả Eco và Plus (2 trước, 2 rèm, 2 hông trước, 2 hông sau, 2 bảo vệ chân, 1 trung tâm)",
        "ABS, EBD, BA, ESC, TCS, HSA, ROM, ESS, dTPMS",
        "Cảnh báo chống trộm và cứu hộ tự động",
      ],
    },
    {
      id: "adas",
      heading: "ADAS Cấp Độ 2",
      headingLevel: 2,
      items: [
        "Hỗ trợ lái trên cao tốc và khi tắc đường",
        "Ga tự động thích ứng, điều chỉnh tốc độ thông minh",
        "Nhận biết biển báo giao thông",
        "Cảnh báo va chạm trước/sau, điểm mù, mở cửa",
        "Phanh tự động khẩn cấp, hỗ trợ giữ làn khẩn cấp",
        "Camera sau, giám sát xung quanh, giám sát lái xe",
      ],
    },
    {
      id: "cong-nghe",
      heading: "Công Nghệ Thông Minh",
      headingLevel: 2,
      items: [
        "Trợ lý ảo AI hỗ trợ tiếng Việt, điều khiển xe bằng giọng nói",
        "Cập nhật phần mềm OTA",
        "Ứng dụng điện thoại: giám sát, điều khiển, tìm trạm sạc",
        "Dẫn đường, trình duyệt web, giải trí trực tuyến, trò chơi",
        "Bậc lên xuống điện (Plus)",
      ],
    },
    {
      id: "mua-lai",
      heading: "Tỷ Lệ Mua Lại",
      headingLevel: 2,
      items: [
        "≤ 6 tháng: mua lại 90% · đổi xe 93%",
        "12 tháng: mua lại 86% · đổi xe 89%",
        "24 tháng: mua lại 78% · đổi xe 81%",
        "36 tháng: mua lại 70% · đổi xe 73%",
      ],
    },
  ],
  warrantyItems: [
    "Bảo hành xe: 10 năm hoặc 200.000 km",
    "Bảo hành pin: 10 năm hoặc 200.000 km",
    "Sạc điện miễn phí 2 năm đến 30/06/2027 tại trạm VinFast công cộng",
  ],
  afterSalesItems: [
    "Giao nhận xe tận nơi miễn phí trong bán kính 30 km (giờ hành chính)",
    "Hotline CSKH 24/7 chuyên trách",
    "150.000 cổng sạc phủ 34/34 tỉnh thành",
  ],
  targetAudience: [
    "Người thành đạt, tiên phong",
    "Khách hàng cần SUV điện 7 chỗ hạng sang",
  ],
  disclaimerNotes: [
    "Một số tính năng sẽ được kích hoạt sau qua cập nhật OTA.",
    "Quãng đường thực tế có thể thấp hơn WLTP tùy điều kiện vận hành.",
    "Thông số sản phẩm có thể thay đổi mà không báo trước.",
  ],
  features: [
    "SUV điện 7 chỗ hạng sang",
    "Pin 123 kWh, quãng đường đến 626 km WLTP",
    "ADAS cấp độ 2 trên cả Eco và Plus",
    "Bảo hành 10 năm/200.000 km",
    "Sạc miễn phí 2 năm tại trạm công cộng VinFast",
  ],
};
